services:
  user-service:
    image: jakeerbasha123/user-service:latest
    container_name: user-service-deployment
    ports:
      - "8081:8081"

  auth-service:
    image: jakeerbasha123/auth-service:latest
    container_name: auth-service-deployment
    ports:
      - "8082:8082"

  card-service:
    image: jakeerbasha123/card-service:latest
    container_name: card-service-deployment
    ports:
      - "8083:8083"

  transaction-service:
    image: jakeerbasha123/transaction-service:latest
    container_name: transaction-service-deployment
    ports:
      - "8084:8084"

  fraud-detection-service:
    image: jakeerbasha123/fraud-detection-service:latest
    container_name: fraud-detection-service-deployment
    ports:
      - "8085:8085"

  api-gateway:
    image: jakeerbasha123/api-gateway:latest
    container_name: api-gateway-deployment
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "MyBankingAppJwtSecretKeyForDevelopmentOnly2026Secure"